spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.paranoid.ssm01.domain
